version: '3'
services:
  # web:
  #   image: python:3.9
  #   working_dir: /app
  #   volumes:
  #     - ./app:/app
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - POSTGRES_URL=postgresql://postgres:pwd@db:5432/db_name

  tasty_db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: tasty_traverse_development
    ports:
     - 15432:5432