version: '3'
services:
  web:
    container_name: tasty_web
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - tasty_db
    command: >
      bash -c "flask db upgrade && python app.py"

  tasty_db:
    image: postgres:13
    container_name: tasty_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
     - 15432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
